defmodule Potinho.Transaction do
  use Ecto.Schema
  import Ecto.Changeset
  alias Potinho.User

  @primary_key {:id, Ecto.UUID, autogenerated: true}
  schema "transactions" do
    field :amount, Money.Ecto.Amount.Type
    belongs_to :user_sender, User, type: Ecto.UUID
    belongs_to :user_reciever, User, type: Ecto.UUID

    timestamps()
  end

  @required_attrs [:user_reciever_id, :user_sender_id, :amount]

  def create_changeset(params) do
    %__MODULE__{}
    |> cast(params, @required_attrs)
    |> validate_required(@required_attrs)
  end
end
