defmodule Potinho.Transaction do
  use Ecto.Schema
  import Ecto.Changeset
  alias Potinho.User

  @primary_key {:id, Ecto.UUID, autogenerated: true}
  schema "transactions" do
    field :amount, Money.Ecto.Amount.Type
    field :is_chargeback, :boolean, default: false
    belongs_to :user_sender, User, type: Ecto.UUID
    belongs_to :user_reciever, User, type: Ecto.UUID

    timestamps()
  end

  @required_attrs [:user_reciever_id, :user_sender_id, :amount]
  @castable_fields [:user_reciever_id, :user_sender_id, :amount, :is_chargeback]

  def create_changeset(params) do
    %__MODULE__{}
    |> cast(params, @castable_fields)
    |> validate_required(@required_attrs)
  end

  def changeset(changeset, attrs) do
    changeset
    |> cast(attrs, @castable_fields)
  end
end
